// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$nQQOPOOO`OQO'#C_OnOPO'#C^OOOO'#Cm'#CmQQOPOOOOOO'#Ca'#CaO!POQO,59UOOOO,58y,58yOOOO,59U,59UO![OQO'#C_OOOO'#Cn'#CnO!dOPO'#CeOOOO'#Cf'#CfO!uOPO'#CoO#WOPO'#CdO#WOPO'#CdO#fOPO'#C^OOOO,58x,58xOOOO-E6k-E6kOOOO,58{,58{OOOO1G.p1G.pO#nOQO'#CaOOOO-E6l-E6lOOOO,59Z,59ZOOOO-E6m-E6mOOOO,59O,59OO#WOPO,59OOOOO1G.j1G.j",
  stateData: "#v~OSPOZRO[ROeRO~OUUOVTO_WO`WO~OSXOZ[O[[O][OeYO~OVcO_dO`dO~OUeOVTO~OeYOSXXZXX[XX]XX~OeYOScXZcX[cX]cX~OSXOZ[O[[O][O~OSXOeYO~OVcO~OSZ~",
  goto: "#TdPPepP{PP!P!T![PPP!fPP!j!p!xSROSZ]Q^_`jSQOSZ`Q^_`jTVPXTaQ`S_Q`Rg]QWQSi^_RkjTROSQSORbSUZQ]`RfZS^Q`Sh^jRj_",
  nodeNames: "⚠ TextColor Expression TcLeft LMarker Description Color InnerMarker TcRight Text REnd RMarker ENDLN EOF Unfinished ColorEOF ColorWS",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%Z~RaXY!WYZ!]]^!Wpq!Wqr!Wrs!Ws!_!W!_!`!j!`#O!W#O#P!w#P#r!W#r#s$k#s;'S!W;'S;=`%O<%l~!W~O!W~~%U~!]Oe~~!bPe~YZ!e~!jO[~~!oPe~#r#s!r~!wOZ~~!|Xe~rs!W!P!Q!W#O#P!W#U#V!W#Y#Z!W#b#c!W#f#g!W#h#i!W#i#j#i~#lR!Q![#u!c!i#u#T#Z#u~#xR!Q![$R!c!i$R#T#Z$R~$UR!Q![$_!c!i$_#T#Z$_~$bR!Q![!W!c!i!W#T#Z!W~$pPe~!_!`$s~$vP#o#p$y~%OOS~~%RP;=`<%l!W~%ZO]~",
  tokenizers: [1, new LocalTokenGroup("!X~R[X^wpqw#q#r|#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~~!R~|O`~~!ROV~~!WO_~~", 54, 6)],
  topRules: {"TextColor":[0,1]},
  tokenPrec: 127
})
