// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UQQOPOOOYOQO'#C_OhOPO'#C^OOOO'#Cj'#CjQQOPOOOOOO'#Ca'#CaOvOQO,59QOOOO,58y,58yOOOO,59Q,59QO!ROQO'#C_OOOO'#Ck'#CkO!ZOPO,59QO!iOPO'#CdO!iOPO'#C^OOOO,58x,58xOOOO-E6h-E6hOOOO,58{,58{OOOO1G.l1G.lO!qOQO'#CaOOOO-E6i-E6iOOOO,59O,59OO!iOPO,59OO!vOPO'#CdOOOO1G.j1G.j",
  stateData: "#U~OSPOaRO~OUUOVTOZWO[WO~OSXOXWO]WOaYO~OV`OZaO[aO~OUbOVTO~OSXOXdO]aOaYO~OSXOaYO~OV`O~OSXOXdOaYO~OSX~",
  goto: "!q`PPaoP{PP!PP!ZPPP!_!eSROSW[Q[]eTeZfSQOS]]QZ[]efTVPXS^Q]Qd[RgeTROSQSOR_SQZQScZfVf[]e",
  nodeNames: "⚠ TextColor Expression TcLeft LMarker Description Color InnerMarker TcRight RMarker Unfinished ColorEOF ColorWS EOF",
  maxTerm: 17,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "$|~RaXY!WYZ!W]^!Wpq!Wqr!Wrs!Ws{!W{|!]|}!W}!O!j!O#O!W#O#P!}#P;'S!W;'S;=`$q<%l~!W~O!W~~$w~!]Oa~~!bPa~}!O!e~!jOX~~!oPa~{|!r~!uP#o#p!x~!}OS~~#SXa~rs!W!P!Q!W#O#P!W#U#V!W#Y#Z!W#b#c!W#f#g!W#h#i!W#i#j#o~#rR!Q![#{!c!i#{#T#Z#{~$OR!Q![$X!c!i$X#T#Z$X~$[R!Q![$e!c!i$e#T#Z$e~$hR!Q![!W!c!i!W#T#Z!W~$tP;=`<%l!W~$|O]~",
  tokenizers: [1, new LocalTokenGroup("!X~R[X^wpqw#q#r|#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~~!R~|O[~~!ROV~~!WOZ~~", 54, 6)],
  topRules: {"TextColor":[0,1]},
  tokenPrec: 95
})
