// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  TextColor = 1,
  Expression = 2,
  TcLeft = 3,
  LMarker = 4,
  Description = 5,
  Color = 6,
  InnerMarker = 7,
  TcRight = 8,
  RMarker = 9,
  Unfinished = 10,
  ColorEOF = 11,
  ColorWS = 12,
  EOF = 13
