// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  TextColor = 1,
  Expression = 2,
  TcLeft = 3,
  LMarker = 4,
  Description = 5,
  Color = 6,
  InnerMarker = 7,
  TcRight = 8,
  Text = 9,
  RMarker = 10,
  Unfinished = 11,
  ColorEOF = 12,
  ColorWS = 13,
  EOF = 14
