// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$nQQOPOOOYOQO'#C_OhOPO'#C^OOOO'#Ck'#CkQQOPOOOOOO'#Ca'#CaOvOQO,59ROOOO,58y,58yOOOO,59R,59RO!ROQO'#C_OOOO'#Cl'#ClO!ZOPO,59RO!iOPO'#CmO!tOPO'#CdO!tOPO'#CdO!|OPO'#C^OOOO,58x,58xOOOO-E6i-E6iOOOO,58{,58{OOOO1G.m1G.mO#UOQO'#CaOOOO-E6j-E6jO!^OPO'#CeOOOO,59X,59XOOOO-E6k-E6kOOOO,59O,59OO#ZOPO,59OOOOO1G.j1G.j",
  stateData: "#f~OSPOcRO~OUUOVTO[WO]WO~OSXOYWO^WOcYO~OVbO[cO]cO~OUdOVTO~O^cOcYOSXXYXX~OcYOSaXYaX~OSXOYiO~OSXOcYO~OVbO~OSXOYkO~OSY~",
  goto: "!zbPPcnPyPP}!RP!YPPP!^!d!oSROSZ[Q]^_jSQOSZ_Q]^_jTVPXT`Q_S^Q_Rg[TROSQSORaSQZQSeZfTf[_S]Q_Sh]jRj^",
  nodeNames: "⚠ TextColor Expression TcLeft LMarker Description Color InnerMarker TcRight Text RMarker Unfinished ColorEOF ColorWS EOF",
  maxTerm: 19,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "$|~RaXY!WYZ!W]^!Wpq!Wqr!Wrs!Ws{!W{|!]|}!W}!O!j!O#O!W#O#P!}#P;'S!W;'S;=`$q<%l~!W~O!W~~$w~!]Oc~~!bPc~}!O!e~!jOY~~!oPc~{|!r~!uP#o#p!x~!}OS~~#SXc~rs!W!P!Q!W#O#P!W#U#V!W#Y#Z!W#b#c!W#f#g!W#h#i!W#i#j#o~#rR!Q![#{!c!i#{#T#Z#{~$OR!Q![$X!c!i$X#T#Z$X~$[R!Q![$e!c!i$e#T#Z$e~$hR!Q![!W!c!i!W#T#Z!W~$tP;=`<%l!W~$|O^~",
  tokenizers: [1, new LocalTokenGroup("!X~R[X^wpqw#q#r|#y#zw$f$gw#BY#BZw$IS$I_w$I|$JOw$JT$JUw$KV$KWw&FU&FVw~~!R~|O]~~!ROV~~!WO[~~", 54, 6)],
  topRules: {"TextColor":[0,1]},
  tokenPrec: 111
})
